spring:
  main:
    allow-circular-references: true
  port: 8080
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_URL:localhost}:{SPRING_DATASOURCE_PORT:3306}/${SPRING_DATASOURCE_TABLE:playpiece}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
