version: '3.8'
services:
  db:
    image: mysql:8
    container_name: playpiecedb
    restart: always
    environment:
      MYSQL_DATABASE: playpiece
      MYSQL_ROOT_PASSWORD: 123123
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  app:
    build: .
    container_name: playpiece
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
